
package prueba;

import javax.swing.JOptionPane;
import java.awt.BorderLayout ;
//Esta clase contiene la funcion principal  y metodos  necesario para la interfaze grafica
public class Frame1 extends javax.swing.JFrame {

    /**
     * Primer comobo box 
     *mediante un ciclo se generan los items que contendra este como box
     *que representaran los años
     */
    public Frame1() {
        initComponents(); 
         for (int a = 1950; a<=2013 ; a++)
        {
            jahre.addItem( Integer.toString( a ) );
        add(jahre );
        }
      //combo box 2  se mostraran los MESES
         //mes es el nombre  la variable del combo box
        mes.addItem("01");
        mes.addItem("02");
        mes.addItem("03");
        mes.addItem("04");
        mes.addItem("05");
        mes.addItem("06");
        mes.addItem("07");
        mes.addItem("08");
        mes.addItem("09");
        mes.addItem("10");
        mes.addItem("11");
        mes.addItem("12");
        
      // Tag es la variable del comobo box que representara los dias DIAS
        Tag.addItem("01");
        Tag.addItem("02");
        Tag.addItem("03");
        Tag.addItem("04");
        Tag.addItem("05");
        Tag.addItem("06");
        Tag.addItem("07");
        Tag.addItem("08");
        Tag.addItem("09");
        Tag.addItem("10");
        Tag.addItem("11");
        Tag.addItem("12");
        Tag.addItem("13");
        Tag.addItem("14");
        Tag.addItem("15");
        Tag.addItem("16");
        Tag.addItem("17");
        Tag.addItem("18");
        Tag.addItem("19");
        Tag.addItem("20");
        Tag.addItem("21");
        Tag.addItem("22");
        Tag.addItem("23");
        Tag.addItem("24");
        Tag.addItem("25");
        Tag.addItem("26");
        Tag.addItem("27");
        Tag.addItem("28");
        Tag.addItem("29");
        Tag.addItem("30");
        Tag.addItem("31");
     
    //Lugar de nacimiento
        geburstsort.addItem("AGUAS CALIENTES"); 
        geburstsort.addItem("BAJA CALIFORNIA"); 
        geburstsort.addItem("BAJA CALIFORNIA SUR");
        geburstsort.addItem("CAMPECHE"); 
        geburstsort.addItem("COAHUILA"); 
        geburstsort.addItem("COLIMA");
        geburstsort.addItem("CHIAPAS");
        geburstsort.addItem("CHIHUAHUA"); 
        geburstsort.addItem("CIUDAD DE MEXICO");
        geburstsort.addItem("DURANGO"); 
        geburstsort.addItem("GUANAJUATO");
        geburstsort.addItem("GUERRERO"); 
        geburstsort.addItem("HIDALGO"); 
        geburstsort.addItem("JALISCO"); 
        geburstsort.addItem("EDO MEXICO");
        geburstsort.addItem("MICHOACAN"); 
        geburstsort.addItem("MORELOS"); 
        geburstsort.addItem("NAYARIT"); 
        geburstsort.addItem("NUEVO LEON");
        geburstsort.addItem("OAXACA"); 
        geburstsort.addItem("PUEBLA"); 
        geburstsort.addItem("QUERERTARO");
        geburstsort.addItem("QUINTANA ROO"); 
        geburstsort.addItem("SAN LUIS POTOSI"); 
        geburstsort.addItem("SINALOA");
        geburstsort.addItem("SONORA"); 
        geburstsort.addItem("TABASCO"); 
        geburstsort.addItem("TAMAULIPAS"); 
        geburstsort.addItem("TLAXCALA");
        geburstsort.addItem("VERACRUZ"); 
        geburstsort.addItem("YUCATAN"); 
        geburstsort.addItem("ZACATECAS");
        
     //Sexo
        sexo.addItem("M");
        sexo.addItem("H");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido_p = new javax.swing.JTextField();
        apellido_m = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jahre = new javax.swing.JComboBox();
        mes = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Tag = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        schlusselmachen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        geburstsort = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        claveE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellido_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido_pActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año");

        jahre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jahreActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Día");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Nacimiento");

        salir.setForeground(new java.awt.Color(204, 0, 0));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        limpiar.setForeground(new java.awt.Color(51, 204, 0));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mes");

        schlusselmachen.setForeground(new java.awt.Color(51, 204, 0));
        schlusselmachen.setText("Generar Claves");
        schlusselmachen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schlusselmachenActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lugar de nacimiento");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sexo");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CURP");

        curp.setEditable(false);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RFC");

        rfc.setEditable(false);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clave de Elector");

        claveE.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido_m, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido_p, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(68, 68, 68)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(claveE, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rfc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jahre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(geburstsort, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(limpiar)
                                .addComponent(schlusselmachen)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(Tag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jahre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(geburstsort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schlusselmachen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(claveE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpiar)
                            .addComponent(salir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jahreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jahreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jahreActionPerformed

    private void apellido_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido_pActionPerformed
    //se asigna al boton salir la accion de salir del rpograma
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose ( );
    }//GEN-LAST:event_salirActionPerformed
    //al boton limpiar se actualizan los texfield con cadenas vacias
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
       nombre.setText("");
       apellido_p.setText("");
       apellido_m.setText("");
       curp.setText("");
       rfc.setText("");
       claveE.setText("");
    }//GEN-LAST:event_limpiarActionPerformed
    //EStemetodo  que hace referencia al boton de generar claves y valida que todos los campos tengan iinformacion
    private void schlusselmachenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schlusselmachenActionPerformed
        
        if(nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Porfavor ingrese el nombre");
            return;
        }
        if(apellido_p.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Porfavor ingrese el apelldo paterno");
            return;
        }
        if(apellido_m.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Porfavor ingrese el apellido materno");
            return;
        }
        //se crea un objeto de la clase persona  llamado p
        Persona p = new Persona();
        //se le asigna una cadena recivida del texfield a acada atributo de la clase persona
        p.SetNombre(nombre.getText());
        p.SetApellido_P(apellido_p.getText());
        p.SetApellido_M(apellido_m.getText());
        p.SetGeburtsdatum((String)Tag.getSelectedItem(), (String)mes.getSelectedItem(),(String)jahre.getSelectedItem());
        p.SetGeburtsort((String)geburstsort.getSelectedItem());
        p.SetSexo((String)sexo.getSelectedItem());
        p.SetStaatsangehorigkeit((String)geburstsort.getSelectedItem());
        // se mandan a llmar cada uno de los metodos que generaran las claves
        p.CalculaCURP();
        p.CalculaClaveElector();
        p.CalculaRFC();
        //se extraen los atributos CURP, RFC Y CLAVE DE ELECTOS del objeto persona
        //yy se asignan a  el textfiel CURP , REFC Y CLAVE DE ELECTOR respectivamente
        curp.setText(p.getCURP());
        rfc.setText(p.getRFC());
        claveE.setText(p.getClaveE());
    }//GEN-LAST:event_schlusselmachenActionPerformed
    //se edita el fondo del jframe para dar una  mejor apariencia
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FondoFormulario aplicarfondo=new FondoFormulario();
        this.add(aplicarfondo,BorderLayout.SOUTH);
        aplicarfondo.repaint();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
//funcion principal que  muestra  el jframe
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Tag;
    private javax.swing.JTextField apellido_m;
    private javax.swing.JTextField apellido_p;
    private javax.swing.JTextField claveE;
    private javax.swing.JTextField curp;
    private javax.swing.JComboBox geburstsort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jahre;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox mes;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField rfc;
    private javax.swing.JButton salir;
    private javax.swing.JButton schlusselmachen;
    private javax.swing.JComboBox sexo;
    // End of variables declaration//GEN-END:variables
}
